development:
  adapter: postgresql
  encoding: unicode
  database: project_manager_development
  pool: 5
  username: project_manager
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: project_manager_test
  pool: 5
  username: project_manager
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: project_manager_production
  pool: 5
  username: project_manager
  password:
